[workspace]
members = [
  "web-fe",
  "lib/datastructure",
  "lib/datastructure/datastructure_macro_derive",
  "lib/idl-gen",
  "server/web-bss",
  "server/web-cronjob",
  "server/game-backend",
  "server-lib/web-db",
  "server-lib/aliyun-helper",
  "server-lib/feishu-api",
  "server-lib/bilibili-api",
  "game-modules/heartstone",
  "game-modules/heartstone/cli",
]
resolver = "2"

[profile.release.package."game-backend"]
codegen-units = 1
debug = true
debug-assertions = false
incremental = false
opt-level = 3
overflow-checks = false

[profile.release.package."web-fe"]
debug = 0
debug-assertions = false
incremental = false
opt-level = 'z'
overflow-checks = true
strip = "debuginfo"
