[package]
name = "web-bss"
version = "0.1.0"
edition = "2021"

[dependencies]
web-db = { path = "../web-db" }
idl-gen = { path = "../idl-gen" }
rocket = { version = "0.5.0-rc.3", features = ["json"] }
tokio = { version = "1.28.1", features = ["sync"]}
anyhow = "1.0"
log = "0.4.6"
time = "0.3.21"
tokio-websockets = "0.3.2"
rust-crypto = "0.2.36"
base64 = "0.21.2"
lazy_static = "1.4.0"
volo = "*"
volo-grpc = "*"
pilota = "*"
uuid = { version = "1.3.3", features = ["v4"] }
