[package]
edition = "2021"
name = "server-common"
version = "0.1.0"

[dependencies]
anyhow = {version = "1.0.95", features = ["backtrace"]}
chrono = "0.4.39"
futures = "0.3.31"
log = "0.4.25"
sqlx = {version = "0.8.3", features = ["runtime-tokio"]}
tokio = "1.43.0"
tracing = "0.1.41"
