apiVersion: batch/v1
kind: CronJob
metadata:
  name: web-cronjob-fetch-github-activity
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: web-cronjob-fetch-github-activity-container
            image: chushi0/rustweb/web-cronjob
            imagePullPolicy: Never
            env:
              - name: RUST_BACKTRACE
                value: "1"
              - name: RUST_LIB_BACKTRACE
                value: "1"
              - name: RUST_WEB_DB_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: mysql-root-password
                    key: app-username
              - name: RUST_WEB_DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mysql-root-password
                    key: app-password
            workingDir: /usr/local/home
            command: ["/usr/local/home/web-cronjob"]
            args: ["fetch-github-activity"] 
          restartPolicy: Never
