apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-bff-deployment
  labels:
    app: web-bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-bff
  template:
    metadata:
      labels:
        app: web-bff
    spec:
      containers:
        - name: web-bff
          image: chushi0/rustweb/web-bff:latest
          imagePullPolicy: Never
          env:
            - name: RUST_BACKTRACE
              value: "1"
            - name: RUST_LIB_BACKTRACE
              value: "1"
          ports:
            - containerPort: 8080
            - containerPort: 3000
            - containerPort: 13000

---
apiVersion: v1
kind: Service
metadata:
  name: web-bff-service-http
spec:
  selector:
    app: web-bff
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 3000
      targetPort: 13000
      name: websocket
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: web-bff-service-rpc
spec:
  selector:
    app: web-bff
  ports:
    - protocol: TCP
      port: 13000
      targetPort: 13000
  type: ClusterIP