[package]
edition = "2021"
name = "aliyun-helper"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
base64 = "0.21.5"
hmac-sha1 = "0.2.1"
reqwest = "0.11.22"
urlencoding = "2.1.3"
