name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  # Bins
  web-bss:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cd web-bss
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy
  web-cronjob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cd web-cronjob
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy
  game-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cd game-backend
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy

  # Libs
  web-db:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cd web-db
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy
  idl-gen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cd idl-gen
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy
