name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  # Bins
  web-bss:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd web-bss && cargo build --verbose
    - name: Run tests
      run: cd web-bss && cargo test --verbose
    - name: Run clippy
      run: cd web-bss && cargo clippy
  web-cronjob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd web-cronjob && cargo build --verbose
    - name: Run tests
      run: cd web-cronjob && cargo test --verbose
    - name: Run clippy
      run: cd web-cronjob && cargo clippy
  game-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd game-backend && cargo build --verbose
    - name: Run tests
      run: cd game-backend && cargo test --verbose
    - name: Run clippy
      run: cd game-backend && cargo clippy

  # Libs
  web-db:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd web-db && cargo build --verbose
    - name: Run tests
      run: cd web-db && cargo test --verbose
    - name: Run clippy
      run: cd web-db && cargo clippy
  idl-gen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cd idl-gen
    - name: Build
      run: cd idl-gen && cargo build --verbose
    - name: Run tests
      run: cd idl-gen && cargo test --verbose
    - name: Run clippy
      run: cd idl-gen && cargo clippy
